apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data:
  username: c3ByaW5ndXNlcg==       # base64("springuser")
  password: c3ByaW5ncGFzcw==       # base64("springpass")
  rootpassword: cm9vdHBhc3M=       # base64("rootpass")

